import {createReader} from './reader.mjs';
import {createRecordPlayer} from './media.mjs';
import {terminalSession,SESSION_SCHEMA} from './session-core.mjs';
import './local-navigation.mjs';
import {createSpatialGraph} from './graph-view.mjs';
import {KINDS,validateCatalog,selectRecords,validateImport,readURLState} from '../experience-base/archive/core.mjs';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const reader=createReader(),recordPlayer=createRecordPlayer(document.querySelector('#player'),document.querySelector('#player-status'));window.akashicReader=reader;window.akashicMedia=recordPlayer;
const KEY='akashic-terminal-library-v1', prefsKey='akashic-terminal-motion-v1';
let settleSession;const sessionReady=new Promise(resolve=>{settleSession=resolve});
let catalog=null,selected=null,saved=[],visited=[],memoryOnly=false,toastTimer,animation=0;
let state={query:'',kind:'all',chapter:1,savedOnly:false};let requestedChapter=1;
const reduced=matchMedia('(prefers-reduced-motion:reduce)');
let explicitMotion=null;try{explicitMotion=localStorage.getItem(prefsKey)}catch{memoryOnly=true}
let motion=explicitMotion===null?!reduced.matches:explicitMotion==='on';
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function notify(text){const n=$('#toast');const host=$$('dialog').find(d=>d.open)||document.body;host.append(n);n.textContent=text;n.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.hidden=true,5000)}
function restoreLibrary(){try{const data=JSON.parse(localStorage.getItem(KEY)||'null');if(data){const ids=new Set(catalog.records.map(r=>r.id));saved=validateImport(data,ids);visited=Array.isArray(data.visited)?data.visited.filter(v=>typeof v==='string'&&ids.has(v)).slice(-100):[]}}catch{saved=[];visited=[];memoryOnly=true}}
function persist(){try{localStorage.setItem(KEY,JSON.stringify({application:'akashic-terminal',version:1,saved,visited}))}catch{memoryOnly=true;notify('この環境では一時保存になります。JSONで書き出して保管できます。')}}
function toggleSave(id){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];persist();render();updateDetailSave();notify(memoryOnly?'しおりを一時保存しました。JSONの書き出しで保管できます。':saved.includes(id)?'しおりに保存しました。':'しおりを外しました。')}
function replaceURL(url){try{history.replaceState(null,'',url)}catch{/* Sandboxed and local previews may disallow History API. Keep the UI usable. */}}
function urlStateParams(){return new URLSearchParams(location.hash.replace(/^#/,''))}
function setFragment(params){const u=new URL(location.href);for(const k of ['q','kind','chapter','saved','record'])u.searchParams.delete(k);u.hash=params.toString();replaceURL(u)}
function syncQuery(){const q=urlStateParams();for(const [k,v]of Object.entries({q:state.query,kind:state.kind==='all'?'':state.kind,chapter:state.chapter===1?'':String(state.chapter),saved:state.savedOnly?'1':''})){if(v)q.set(k,v);else q.delete(k)}setFragment(q)}
function restoreQuery(){const parsed=readURLState(location.hash.includes('=')?location.hash:location.search);requestedChapter=parsed.requestedChapter;state={query:parsed.query,kind:parsed.kind,chapter:1,savedOnly:parsed.savedOnly};$('#query').value=state.query;$('#chapter').value='1'}
function filtered(){return selectRecords(catalog.records,state,saved)}
function render(){if(!catalog)return;const found=filtered();const cards=$('#cards');cards.replaceChildren();for(const r of found){const c=el('article','card');c.dataset.record=r.id;const top=el('div','card-top');top.append(el('span','card-kind',`EP01 / CH.${String(r.chapter).padStart(2,'0')} / ${KINDS[r.kind]}`),el('span','card-glyph',r.kind==='video'?'▶':r.kind==='text'?'Aa':'♪'));c.append(top,el('h3','',r.title),el('p','',r.description||'文字の書庫に保存された記録。原本をひらいて読む。'));const foot=el('div','card-foot');const open=el('button','inspect','記録をひらく →');open.addEventListener('click',()=>openRecord(r.id));const save=el('button','save',saved.includes(r.id)?'しおり済み':'しおり');save.setAttribute('aria-pressed',String(saved.includes(r.id)));save.setAttribute('aria-label',`${r.title}のしおり`);save.addEventListener('click',()=>{toggleSave(r.id);requestAnimationFrame(()=>{const match=$$('.card').find(c=>c.dataset.record===r.id);(match?.querySelector('.save')||$('#saved-only')).focus()})});foot.append(open,save);c.append(foot);cards.append(c)}
 $('#count').textContent=`${found.length}件を表示 / 索引 ${catalog.records.length}件`;$('#empty').hidden=found.length>0;$('#saved-count').textContent=String(saved.length);$('#saved-only').setAttribute('aria-pressed',String(state.savedOnly));$$('[data-kind]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.kind===state.kind)));renderGraph(found);syncQuery()}
const spatialGraph=createSpatialGraph({shell:document.querySelector('.graph-shell'),host:document.querySelector('#graph-nodes'),onSelect:id=>openRecord(id)});window.akashicGraph=spatialGraph;
function renderGraph(records){spatialGraph.update(records)}
function updateDetailSave(){if(!selected)return;$('#detail-save').textContent=saved.includes(selected.id)?'しおりを外す':'しおりに保存';$('#detail-save').setAttribute('aria-pressed',String(saved.includes(selected.id)))}
function clearPlayer(){recordPlayer.close();$('#player').replaceChildren();$('#play-video').hidden=false;}
function openRecord(id,{fromURL=false}={}){const r=catalog?.records.find(x=>x.id===id);if(!r)return;if(r.chapter>state.chapter){notify('先の章の記録です。「見せる範囲」を広げてからひらいてください。');return}selected=r;clearPlayer();$('#detail-meta').textContent=`EP01 / 第${r.chapter}章 / ${KINDS[r.kind]} / ${r.id}`;$('#detail-title').textContent=r.title;$('#detail-description').textContent=r.description||'掲載元の書庫から、この章の文字記録をひらきます。';$('#record-open').href=r.url;$('#record-open').textContent=r.kind==='audio'?'音声書庫でこの章を選ぶ ↗':'記録の原本をひらく ↗';$('#visited-note').textContent=visited.includes(r.id)?'このブラウザーで以前ひらいた記録です。視聴完了を意味しません。':'しおりとアクセス履歴はこのブラウザーに保存されます。';$('#video-consent').hidden=r.kind!=='video';$('#read-here').hidden=r.kind!=='text';$('#provenance').textContent=`出典: ${r.source} / コミット ${catalog.sourceCommit} / メタデータ確認日 ${catalog.asOf} / 実再生・最新の公開状態: 未確認`;const related=$('#related');related.replaceChildren();catalog.records.filter(x=>x.chapter===r.chapter&&x.id!==id).forEach(x=>{const b=el('button','',`${KINDS[x.kind]} / ${x.title}`);b.addEventListener('click',()=>openRecord(x.id));related.append(b)});if(!related.children.length)related.append(el('p','sub','この索引には、同じ章の別形式はまだありません。'));updateDetailSave();if(!$('#detail').open)$('#detail').showModal();const q=urlStateParams();q.set('record',id);setFragment(q);if(!fromURL)$('#detail-title').scrollIntoView({block:'nearest'})}
function markOpened(){if(selected){visited=[...visited.filter(v=>v!==selected.id),selected.id].slice(-100);persist()}}
$('#record-open').addEventListener('click',markOpened);$('#detail-save').addEventListener('click',()=>selected&&toggleSave(selected.id));
$('#read-here').addEventListener('click',()=>{if(selected)reader.open(selected);});
$('#play-video').addEventListener('click',async()=>{if(!selected||selected.kind!=='video')return;const record=selected;clearPlayer();$('#play-video').hidden=true;markOpened();const ok=await recordPlayer.connect(record);if(!ok&&selected?.id===record.id)$('#play-video').hidden=false;});
$('#record-share').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);notify('この記録へのリンクをコピーしました。')}catch{notify('コピーが許可されていません。ブラウザーのアドレスを共有してください。')}});
$$('dialog').forEach(d=>d.addEventListener('close',()=>{const toast=d.querySelector('#toast');if(toast){document.body.append(toast);toast.hidden=true}}));
$('#detail').addEventListener('cancel',()=>{clearPlayer();reader.close();});
function closeDialog(dialog){if(dialog.id==='detail'){clearPlayer();reader.close();}dialog.close();}
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeDialog(document.getElementById(b.dataset.close))));$('#detail').addEventListener('close',()=>{clearPlayer();reader.close();selected=null;const q=urlStateParams();q.delete('record');setFragment(q)});
// Keep keyboard focus within the active dialog, including reverse Tab at its first control.
$$('dialog').forEach(d=>d.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const controls=[...d.querySelectorAll('button,a[href],input,select,textarea,summary,[tabindex]')].filter(n=>!n.disabled&&n.tabIndex>=0&&n.getClientRects().length);const first=controls[0],last=controls.at(-1);if(!first)return;if(e.shiftKey&&(document.activeElement===first||!d.contains(document.activeElement))){e.preventDefault();last.focus()}else if(!e.shiftKey&&(document.activeElement===last||!d.contains(document.activeElement))){e.preventDefault();first.focus()}}));
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog(d)}));
$('#settings-open').addEventListener('click',()=>$('#settings').showModal());$('#query').addEventListener('input',()=>{state.query=$('#query').value.slice(0,300);render()});$('#chapter').addEventListener('change',()=>{state.chapter=Number($('#chapter').value);render()});$$('[data-kind]').forEach(b=>b.addEventListener('click',()=>{state.kind=b.dataset.kind;render()}));$('#saved-only').addEventListener('click',()=>{state.savedOnly=!state.savedOnly;render()});$('#reset').addEventListener('click',()=>{state.query='';state.kind='all';state.savedOnly=false;$('#query').value='';render();$('#query').focus()});
function focusSearch(){$('#query').scrollIntoView({block:'center'});$('#query').focus()}
$('#focus-search').addEventListener('click',focusSearch);document.addEventListener('keydown',e=>{if($$('dialog').some(d=>d.open))return;const input=['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||e.target.isContentEditable;if((e.key.toLowerCase()==='k'&&(e.ctrlKey||e.metaKey))||(e.key==='/'&&!input)){e.preventDefault();focusSearch()}});$('#start-record').addEventListener('click',()=>openRecord('yt-dlylAw7GHd0'));
$('#export').addEventListener('click',()=>{const b=new Blob([JSON.stringify({application:'akashic-terminal',version:1,saved},null,2)],{type:'application/json'});const u=URL.createObjectURL(b);const a=el('a');a.href=u;a.download='akashic-bookmarks.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);notify('しおりを書き出しました。閲覧履歴は含みません。')});
$('#import').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{if(!catalog||file.size>131072)throw new Error('ファイルが大きすぎるか、索引をまだ読み込んでいません');const incoming=validateImport(JSON.parse(await file.text()),new Set(catalog.records.map(r=>r.id)));saved=[...new Set([...saved,...incoming])];persist();render();updateDetailSave();notify(`${incoming.length}件のしおりを取り込みました。${memoryOnly?'一時保存です。':''}`)}catch(error){notify(`取り込めませんでした: ${error.message}`)}finally{e.target.value=''}});
addEventListener('storage',e=>{if(e.key===KEY&&catalog){restoreLibrary();render();updateDetailSave()}});
async function load(){try{const requestedRecord=readURLState(location.hash.includes('=')?location.hash:location.search).record;let data=window.__AKASHIC_BUNDLED_CATALOG__;if(!data){const response=await fetch(new URL('../experience-base/archive/catalog.json',import.meta.url),{cache:'no-cache'});if(!response.ok)throw new Error('HTTP '+response.status);data=await response.json()}catalog=validateCatalog(data);restoreLibrary();restoreQuery();$('#load-error').hidden=true;$('#source-note').textContent=`出典確認 ${catalog.asOf} / ${catalog.records.length}件の掲載メタデータ。全動画の台帳ではありません。実再生・最新公開状態・クラウド同期は未確認。`;render();if(requestedChapter>1)notify('共有リンクの先の章はまだ表示していません。「見せる範囲」を選んでください。');if(requestedRecord)openRecord(requestedRecord,{fromURL:true});settleSession(true)}catch{catalog=null;$('#load-error').hidden=false;$('#count').textContent='索引を読み込めませんでした';settleSession(false)}}$('#retry').addEventListener('click',load);
// Local, bounded animation. No false network status, no sound, no generated canon.
const canvas=$('#plexus'),ctx=canvas.getContext('2d');let w=1,h=1,last=0,t=0,intersect=true;
const points=Array.from({length:75},(_,i)=>{const y=1-2*(i+.5)/75,r=Math.sqrt(1-y*y),a=i*Math.PI*(3-Math.sqrt(5));return{x:Math.cos(a)*r,y,z:Math.sin(a)*r}});
const edges=[];points.forEach((a,i)=>points.forEach((b,j)=>{if(i<j&&(a.x-b.x)**2+(a.y-b.y)**2+(a.z-b.z)**2<.31)edges.push([i,j])}));
function paint(){if(!ctx)return;ctx.clearRect(0,0,w,h);const scale=Math.min(h*.38,w*.32),cx=w*.76,cy=h*.46,a=t*.00006;const pp=points.map(p=>({x:cx+(p.x*Math.cos(a)+p.z*Math.sin(a))*scale,y:cy+p.y*scale,z:-p.x*Math.sin(a)+p.z*Math.cos(a)}));for(const[i,j]of edges){const a=pp[i],b=pp[j];ctx.strokeStyle=`rgba(166,213,210,${.05+(a.z+b.z+2)*.035})`;ctx.lineWidth=.65;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}pp.forEach((p,i)=>{ctx.fillStyle=i%11?'rgba(188,226,220,.6)':'#dcc797';ctx.beginPath();ctx.arc(p.x,p.y,i%11?1.3:2,0,7);ctx.fill()});ctx.strokeStyle='rgba(216,196,151,.28)';ctx.beginPath();ctx.ellipse(cx,cy,scale*1.3,scale*.4,-.3,0,Math.PI*2);ctx.stroke()}
function tick(time){animation=0;if(!motion||!intersect||document.hidden||!ctx)return;if(time-last>33){t+=Math.min(time-last,70);last=time;paint()}animation=requestAnimationFrame(tick)}
function restart(){cancelAnimationFrame(animation);animation=0;last=performance.now();paint();if(motion&&intersect&&!document.hidden&&ctx)animation=requestAnimationFrame(tick)}
function motionUI(){$('#motion').textContent=motion?'動きを止める':'動きを再開する';$('#motion').setAttribute('aria-pressed',String(motion));document.body.classList.toggle('still',!motion);restart()}
function resize(){const r=canvas.parentElement.getBoundingClientRect();w=r.width;h=r.height;const d=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);ctx?.setTransform(d,0,0,d,0,0);restart()}
$('#motion').addEventListener('click',()=>{motion=!motion;explicitMotion=motion?'on':'off';try{localStorage.setItem(prefsKey,explicitMotion)}catch{}motionUI()});reduced.addEventListener('change',()=>{if(explicitMotion===null){motion=!reduced.matches;motionUI()}});if('ResizeObserver'in window)new ResizeObserver(resize).observe(canvas.parentElement);else addEventListener('resize',resize);if('IntersectionObserver'in window)new IntersectionObserver(([e])=>{intersect=e.isIntersecting;restart()}).observe(canvas.parentElement);document.addEventListener('visibilitychange',restart);resize();motionUI();
function connectivity(){$('#connection-state').textContent=navigator.onLine?'端末内検索 / APIキー不要':'オフライン / 保存した索引を表示'}addEventListener('online',connectivity);addEventListener('offline',connectivity);connectivity();
document.querySelector('#offline-status').textContent='0.4拡張のオフライン一式保存は未対応。既存書庫の機能とは別に検証します。';
load();

window.akashicArchiveSession={
 snapshot(){if(!catalog)return null;return terminalSession({schema:SESSION_SCHEMA,state,graph:spatialGraph.getState(),scrollY:window.scrollY,selected:selected?.id||null});},
 async restore(value){
  let clean;try{clean=terminalSession(value)}catch{return false;}if(!await sessionReady||!catalog)return false;
  if(!Array.from($('#chapter').options).some(o=>Number(o.value)===clean.state.chapter))return false;
  state={...clean.state};$('#query').value=state.query;$('#chapter').value=String(state.chapter);render();spatialGraph.restore(clean.graph);
  const record=catalog.records.find(r=>r.id===clean.selected&&r.chapter<=state.chapter);if(record)openRecord(record.id,{fromURL:true});
  requestAnimationFrame(()=>requestAnimationFrame(()=>window.scrollTo({top:clean.scrollY,behavior:'instant'})));return true;
 }
};

addEventListener('pagehide',()=>{recordPlayer.close();reader.dispose();},{once:true});

const mediaControls=document.querySelector('#media-controls');document.querySelector('#player').addEventListener('akashic:mediachange',()=>{const s=recordPlayer.getState().state;mediaControls.hidden=!['ready','playing','paused','ended'].includes(s);document.querySelector('#media-play').disabled=s==='playing';document.querySelector('#media-pause').disabled=s!=='playing';});document.querySelector('#media-play').addEventListener('click',()=>recordPlayer.play());document.querySelector('#media-pause').addEventListener('click',()=>recordPlayer.pause());
